### ISSUE TITLE
how to Read

### ISSUE THREAD

**Issue by rosbeef** [luketimothyjones/ESP-SPI-Flasher#1]
Hi, I try to recover a camera which one i have a spare.
I would copy the rom from the working one to the bricked one.
Does your code permit's to read the working firmware  and storeit to a file ? How to ?
Regards

**Comment by samipfjo** [comment]
Sorry, the present code only supports writes, eg. data flow from PC->ESP->ROM. Given the general communication framework that the codebase lays out, it wouldn't be _super_ hard to add dumping a ROM, but that's not a feature that presently exists.

**Comment by rosbeef** [comment]
thank you for the rapid response .
I don't know how to lead with the code so i pass ;)
Do you know other project which use an esp32 to read a rom ? i see nothing from now.

**Comment by samipfjo** [comment]
That's totally fair; certainly no expectations from me!

The commit timestamps are presently misleading due to an accident while modifying the repo; it's actually been 3-4 years since I've touched this codebase. So it's been a while since I've had my eye on the current state of things, and I'm really not sure what all is available out there. Do you have access to a raspberry pi or a clone thereof?

**Comment by rosbeef** [comment]
No problem i understand that it's software "libre" and greet you for your share even if it don't cover my needs ;)
And nop i only have an esp32-c6-devkitc-1 and at least for this next 6 month no money to buy an other hardware to do that.
So, thank you.

**Comment by samipfjo** [comment]
So, fair warning, I haven't tested this beyond ensuring the code compiles and the python script vaguely runs, but I've added reading for you! Let me know if it works (or doesn't). It'll be a Christmas miracle if it does, but I don't have time to throw together test hardware right now.

Follow the existing directions and then run
`python spi_flasher.py -port PORT_HERE -file flash_dump.bin -baud 921600 --read`

Like with flashing, if you can't get it to work try lower the baud rate ([here's a table of baud rates](https://lucidar.me/en/serialib/most-used-baud-rates-table/)). Once you get to "Read in progress..." give it 10 minutes or so and if it doesn't display "Read complete!" in your terminal it probably isn't working.

[esp-spi-flasher.zip](https://github.com/user-attachments/files/18248400/esp-spi-flasher.zip)

Happy holidays!

**Comment by rosbeef** [comment]
:evergreen_tree: hoooooo, so much thanks, I will try it as soon as i go back home. :crossed_fingers:

**Comment by samipfjo** [comment]
Had some free time and thew together a test setup. I can confirm it is not yet working, but I'll get it working in the next few days and will post again once it is!

**Comment by rosbeef** [comment]
Thanks i'm back home but i have another gift : potable water at home, but i have to connect to the grid so take your time. will be fully free on the first maybe before but those days i'm full :)
Thanks

**Comment by samipfjo** [comment]
That's quite the gift, and a huge quality of life improvement! You focus on that and I'll work on getting this working for you as I'm able!

**Comment by rosbeef** [comment]
i'm free, but take your time :D new year day is a difficult day for the brain :)

**Comment by samipfjo** [comment]
Okay I managed to get an exact dump of my test flash. This is a bit flimsy and may well have problems, but here it is! [esp-spi-flasher.zip](https://github.com/user-attachments/files/18284815/esp-spi-flasher.zip)

Don't provide the baud rate, just do `python spi_flasher.py -port PORT_HERE -file flash_dump.bin --read` . For some reason I couldn't get setting the baud rate arbitrarily over serial working properly in the time that I had. It will create two files, one named `flash_dump.bin` and another named `flash_dump.bin.hex`. The latter is a backup of the hexadecimal version in case converting the dumped bytes to binary fails, as dumping takes 10+ minutes, so a small error would be REALLY annoying.

Let me know if you run into any issues (or if it works)!

**Comment by samipfjo** [comment]
[Here's a pinout](https://cdn.shopify.com/s/files/1/0609/6011/2892/files/doc-esp32-pinout-reference-wroom-devkit.png) for a standard WROOM ESP32 dev board. The pins you'll need to connect to are on the right side preceded by `VSPI_`

**Comment by rosbeef** [comment]
My [esp32c6 dev kit c1](https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32c6/esp32-c6-devkitc-1/user_guide_v1.1.html) is only esp-idf does this affect your script ?

I have this pinout  ![image](https://github.com/user-attachments/assets/bb3b6c25-c071-4921-82f0-70d0f24d5d4c)
I suppose fspi(hd|wp|cs0|clk|id|iq) are the pin to use.

My cam spi flash chip is [this](https://www.lcsc.com/datasheet/lcsc_datasheet_2411201841_BOYAMICRO-BY25Q64ASSIG_C383793.pdf).
![image](https://github.com/user-attachments/assets/0a5f79ac-128d-4944-aa3f-e9d4c869c796)
What i don't know, which of esp fspid or fspiq correspond to flash so or si.

**Comment by samipfjo** [comment]
Yep, you're on the right track!

I found this in the [datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-c6_datasheet_en.pdf) for the ESP32-C6. Looks like FSPID is input and FSPIQ is output.

![image](https://github.com/user-attachments/assets/5f46d18e-61d5-41c1-a1fc-2722579230d7)

The pinout for your flash chip is the same as the example one (seen below), but since you're only doing a read you can modify the wiring slightly to add a layer of protection against overwriting the chip. Instead of wiring WP to VCC, wire it to VSS. Pulling WP low disables writes (Write Protect) but won't affect reads (in our case). Keep HOLD wired to VCC.

![image](https://github.com/user-attachments/assets/d63d6d2d-d47e-4432-81cf-44d74ded8081)

(MI)SO -> Serial Out and (MO)SI -> Serial In, so you'll want to wire FSPIQ to SO and FSPID to SI. If that doesn't work, flip them around; fortunately having them in the wrong orientation won't cause any harm other than not working (which I am *very* grateful for haha)

**Comment by rosbeef** [comment]
ok i saw this example, i didn't notice the black point on the yellow and red line. so as i understand it is a connection to vcc.
Ok so in my case wp should be connected to vss to do a write protection hold stay connected to vcc.

i have problem to compile for espidf.
i change  in main.cpp #include <ErriezCRC32.h> to #include <CRC32.h> (and so in platformio.ini  erriez/ErriezCRC32@^1.0.1 to robtillaart/CRC@^1.0.3 )
and densaugeo/base64 to isdn/B64@^1.0.4
but i stuck on md5 and SPIMemory  i can not find a espidf compatible lib.

**Comment by samipfjo** [comment]
[main.cpp.txt](https://github.com/user-attachments/files/18288010/main.cpp.txt)

File extension modified to make github let me upload it here.

The function signatures are most likely different for the other libraries, so it probably won't work without adapting the code accordingly.

**Comment by rosbeef** [comment]
:/ i will try if pioarduino works with my board and let your code intact.

**Comment by rosbeef** [comment]
ok so I flashed the firmware on my esp3-c6-wroom-1 with pioarduino and your code.


>  *  Executing task: platformio run --target upload 
> 
> Processing nodemcuv2 (platform: espressif32; board: esp32-c6-devkitc-1; framework: arduino)
> --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> Verbose mode can be enabled via `-v, --verbose` option
> CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-c6-devkitc-1.html
> PLATFORM: Espressif 32 (51.3.0-x-stable) > Espressif ESP32-C6-DevKitC-1
> HARDWARE: ESP32C6 160MHz, 320KB RAM, 8MB Flash
> DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-builtin, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
> PACKAGES: 
>  - framework-arduinoespressif32 @ 3.0.7 
>  - framework-arduinoespressif32-libs @ 5.1.0+sha.632e0c2a9f 
>  - tool-esptoolpy @ 4.8.1 
>  - tool-mkfatfs @ 2.0.1 
>  - tool-mklittlefs @ 3.2.0 
>  - tool-mkspiffs @ 2.230.0 (2.30) 
>  - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
>  - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
>  - toolchain-riscv32-esp @ 12.2.0+20230208
> LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
> LDF Modes: Finder ~ chain, Compatibility ~ soft
> Found 43 compatible libraries
> Scanning dependencies...
> Dependency Graph
> |-- SPIMemory @ 3.4.0
> |-- base64 @ 1.4.0
> |-- ErriezCRC32 @ 1.0.1
> |-- SPI @ 3.0.7
> Building in debug mode
> Retrieving maximum program size .pio/build/nodemcuv2/firmware.elf
> Checking size .pio/build/nodemcuv2/firmware.elf
> Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
> RAM:   [=         ]   6.8% (used 22400 bytes from 327680 bytes)
> Flash: [==        ]  20.2% (used 265388 bytes from 1310720 bytes)
> Configuring upload protocol...
> AVAILABLE: cmsis-dap, esp-bridge, esp-builtin, esp-prog, espota, esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
> CURRENT: upload_protocol = esptool
> Looking for upload port...
> 
> Warning! Please install `99-platformio-udev.rules`. 
> More details: https://docs.platformio.org/en/latest/core/installation/udev-rules.html
> 
> Auto-detected: /dev/ttyUSB0
> Uploading .pio/build/nodemcuv2/firmware.bin
> esptool.py v4.8.1.1
> Serial port /dev/ttyUSB0
> Connecting....
> Chip is ESP32-C6 (QFN40) (revision v0.1)
> Features: WiFi 6, BT 5, IEEE802.15.4
> Crystal is 40MHz
> MAC: f0:f5:bd:ff:fe:01:91:7c
> BASE MAC: f0:f5:bd:01:91:7c
> MAC_EXT: ff:fe
> Uploading stub...
> Running stub...
> Stub running...
> Changing baud rate to 921600
> Changed.
> Configuring flash size...
> Auto-detected Flash size: 8MB
> Flash will be erased from 0x00000000 to 0x00004fff...
> Flash will be erased from 0x00008000 to 0x00008fff...
> Flash will be erased from 0x0000e000 to 0x0000ffff...
> Flash will be erased from 0x00010000 to 0x00054fff...
> SHA digest in image updated
> Compressed 19648 bytes to 12545...
> Writing at 0x00000000... (100 %)
> Wrote 19648 bytes (12545 compressed) at 0x00000000 in 0.4 seconds (effective 380.5 kbit/s)...
> Hash of data verified.
> Compressed 3072 bytes to 146...
> Writing at 0x00008000... (100 %)
> Wrote 3072 bytes (146 compressed) at 0x00008000 in 0.1 seconds (effective 488.9 kbit/s)...
> Hash of data verified.
> Compressed 8192 bytes to 47...
> Writing at 0x0000e000... (100 %)
> Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.1 seconds (effective 678.6 kbit/s)...
> Hash of data verified.
> Compressed 282608 bytes to 151859...
> Writing at 0x00010000... (10 %)
> Writing at 0x0001c658... (20 %)
> Writing at 0x00024b2d... (30 %)
> Writing at 0x0002ae4c... (40 %)
> Writing at 0x00032583... (50 %)
> Writing at 0x00039cf9... (60 %)
> Writing at 0x00040a26... (70 %)
> Writing at 0x00047220... (80 %)
> Writing at 0x0004d522... (90 %)
> Writing at 0x000535a7... (100 %)
> Wrote 282608 bytes (151859 compressed) at 0x00010000 in 10.6 seconds (effective 213.7 kbit/s)...
> Hash of data verified.
> 
> Leaving...
> Hard resetting via RTS pin...
> ============================================================================ [SUCCESS] Took 15.96 seconds ============================================================================
>  *  Terminal will be reused by tasks, press any key to close it. 


i try the flasher and i receive : 

$ python3 spi_flasher.py -port /dev/ttyUSB0 -file flash_dump.bin -baud 921600 --read
Connecting...
Initiating connection...
```

Traceback (most recent call last):
  File "/home/mdp/Documentos/Romain/camara/esp-spi-flasher/pc_side/spi_flasher.py", line 385, in <module>
    main()
  File "/home/mdp/Documentos/Romain/camara/esp-spi-flasher/pc_side/spi_flasher.py", line 357, in main
    if initialize_device(args.port, args.baud) is True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mdp/Documentos/Romain/camara/esp-spi-flasher/pc_side/spi_flasher.py", line 67, in initialize_device
    handle_serial_message(mandatory=True)
  File "/home/mdp/Documentos/Romain/camara/esp-spi-flasher/pc_side/spi_flasher.py", line 244, in handle_serial_message
    raise Exception('Did not receive expected serial message')
Exception: Did not receive expected serial message

```

i don't really understand what does that mean :P

**Comment by samipfjo** [comment]
Okay great! That's excellent news that you managed to get it to compile!

At the top of the .py file there's a line something like `VERBOSE_LOGGING = False`; change that `False` to `True`, run it again, and post the full output of the program itself as you did before. You don't need to reupload the binary to the ESP32 since it's not being changed.

Also, every time you are about to run the Python script, unplug and plug back in the ESP32 -- it resets it to the state the script expects.

**Comment by rosbeef** [comment]
damn! i had the first just 1 time and the 2nd 1 time too rest of time i have the last error

```
Connecting...
Initiating connection...
Sending message: "*"

Flash info:
Sending message: "("
-> JEDEC ID: 0xFDF5F5
-> Man ID: 0xFD
-> Memory ID: 0xF5
-> Capacity: 0
-> Max Pages: 0


Read in progress...
Sending message: ")"

Read complete!

```
or 
```
Connecting...
Initiating connection...
Sending message: "*"
Got un-decodeable message: b'\xffx\x00\x00x\x00\x00x\x00\x00x\x00\x00x\x00\x00x\x00\x00\xf88\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\x18\xf8\xf88\x188888888888888888888888888888888888888888888\x1888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888\x18888888888888888888888888888888\x188888888888888888888888888888888888888888888888888888888888888888\xf8\x00x\x00\x00x\x00\x00x\x00\x00x\x00\x00x\x00\x00x\x00\x00x\x00\x00x\x00x\x00x\x00\xf88888888888888888888888888888888888888\x1888888888888888888888888888888888888888888888888888888888888888\xf8\xf888888\xf88\xf888888888\xfe\xf88\x18888888888\xf888888888\xf8\xff'

Flash info:
Sending message: "("

Traceback (most recent call last):
  File "/home/mdp/Documentos/Romain/camara/esp-spi-flasher/pc_side/spi_flasher.py", line 385, in <module>
    main()
  File "/home/mdp/Documentos/Romain/camara/esp-spi-flasher/pc_side/spi_flasher.py", line 357, in main
    if initialize_device(args.port, args.baud) is True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mdp/Documentos/Romain/camara/esp-spi-flasher/pc_side/spi_flasher.py", line 75, in initialize_device
    handle_serial_message(mandatory=True)
  File "/home/mdp/Documentos/Romain/camara/esp-spi-flasher/pc_side/spi_flasher.py", line 244, in handle_serial_message
    raise Exception('Did not receive expected serial message')
Exception: Did not receive expected serial message

```

**Comment by rosbeef** [comment]
How your esp code know which pin are fspi's pins ?

**Comment by samipfjo** [comment]
This suggests that something has gone wrong with the software on the ESP32. If it's failing to connect to the flash it should be displaying an error.

Have you double-checked your wiring? I have on a number of occasions miscounted the pins by one and gotten the connections misplaced. Miswiring can sometimes cause the ESP32 to bootloop, which would cause this symptom.

You can manually specify pins by uncommenting the DEFINEs at the top (SS = CS), uncommenting

uint8_t SPI_PINS[4] = {SPI_SCLK, SPI_MISO, SPI_MOSI, SPI_SS};
SPIFlash flash(*SPI_PINS);

and commenting out
SPIFlash flash;
which is worth a try.

**Comment by samipfjo** [comment]
Oh wait, that first output is correct aside from the flash size getting detected incorrectly! That second output looks suspiciously like a stack trace (eg, the ESP32 crashed and reset). Make sure you unplug/replug between attempts; like I said, it's pretty flimsy right now and frequently doesn't recover gracefully when something goes wrong.

**Comment by samipfjo** [comment]
In `void main()` there's a line that says `flash.begin();`; change that to `flash.begin(M(64));` Your flash chip probably isn't natively supported by SPIMemory, but using that line could very well make it work anyway

**Comment by rosbeef** [comment]
i check and recheck cable wiring i get :
```
$ python3 spi_flasher.py -port /dev/ttyUSB0 -file flash_dump.bin -baud 115200 --read
Connecting...
Initiating connection...
Sending message: "*"

Flash info:
Sending message: "("
-> JEDEC ID: 0xD0C0C0
-> Man ID: 0xD0
-> Memory ID: 0xC0
-> Capacity: 0
-> Max Pages: 0

Sending message: "!115200"
-> Switching to 115200 baud
Got un-decodeable message: b'\x00\x00\x80\x80\x00\x80\x80\x00\x00\x80\x00'

Read in progress...
Sending message: ")"
..........

```

but its not stable sometime works sometime not (disconnecting and reconnecting usb)
maybe my cables are not so good quality.

i recognized the error when usb is not unpluged repluged on reruning the command :

> File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 595, in read
>     raise SerialException(
> serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

and now it sometime appear but did not touch anything: 

> File "/home/mdp/Documentos/Romain/camara/esp-spi-flasher/pc_side/spi_flasher.py", line 263, in handle_serial_message
>     raise Exception(message_data.replace('ERROR: ', ''))
> Exception: Connection to flash failed; check wiring.

Let me wait for 10 min as you say.
FI my flash is this one maybe you are more aware of seeing something interesting : https://www.lcsc.com/datasheet/lcsc_datasheet_2411201841_BOYAMICRO-BY25Q64ASSIG_C383793.pdf

**Comment by rosbeef** [comment]
nothing append after 20min  and bin file is empty.

flash.begin(M(64)) ; report me an error on the compiler.
flash.begin(MB(64)) build but give me the same error with spi_flasher

> Flash info:
> Sending message: "("
> -> JEDEC ID: 0xF4C080
> -> Man ID: 0xF4
> -> Memory ID: 0xC0
> -> Capacity: 0
> -> Max Pages: 0

seems to no correspond to my flash and change randomly.
![image](https://github.com/user-attachments/assets/36e4e66f-32ee-4fdd-992b-4f03163139b4)

**Comment by rosbeef** [comment]
Reading a bit more my chip is compatible with JESD216 which should work with SPIMemory project, and instruction specified in the defines.h file (inside the spimemory project) are compatible.

I don't see any information why "(" message return random values.
Maybe we should stop here i don't want to take more of your time. :)

**Comment by samipfjo** [comment]
[esp-spi-flasher.zip](https://github.com/user-attachments/files/18470220/esp-spi-flasher.zip)

Try this. Runtime adjustment of baud rate was super flaky, so baud rate is now hard-coded. It can be changed by modifying `DEFAULT_BAUD_RATE` at the top of both `main.cpp` and `spi_flasher.py`. I already added `MB(64)` into the code for you.

**Comment by samipfjo** [comment]
Sorry about the delay in response, things suddenly got crazy for me right after the holidays. I'm happy to continue troubleshooting this as I'm able if you're still interested.

**Comment by rosbeef** [comment]
FYI, I saw that i have to uncomment '''#define USES_SFDP''' in the SPIMemory.h to make it work with JESD216 compatible chips but not directly supported by SPIMemory.

I did it before so i try your new flasher now....

I'm really interested but we are free as the freesoftware, so there is no delay ;) take your time.

**Comment by rosbeef** [comment]
Nop, i could not make it works. i will need to go deeper in spiflash.h ...

**Comment by rosbeef** [comment]
I don't know whats happening, with all my care and all spiflasher version, it does not detect my chip. "connection problem"

Maybe i did something bad trying to put a capacitance and kill my rom :/ . I need to investigate more but i have no many time until march

**Comment by sysytwl** [comment]
hi, it works. thanks. but need to add a flash size config arg for unknow type of chip.

```cmd

in -baud 921600 --read
Connecting...
Initiating connection...

Flash info:
-> info(error code):Unable to identify chip. Are you sure this chip is supported?

Traceback (most recent call last):
  File "C:\Users\jack\Downloads\esp-spi-flasher (1)\esp-spi-flasher\pc_side\spi_flasher.py", line 385, in <module>
    main()
  File "C:\Users\jack\Downloads\esp-spi-flasher (1)\esp-spi-flasher\pc_side\spi_flasher.py", line 357, in main
    if initialize_device(args.port, args.baud) is True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jack\Downloads\esp-spi-flasher (1)\esp-spi-flasher\pc_side\spi_flasher.py", line 75, in initialize_device
    handle_serial_message(mandatory=True)
  File "C:\Users\jack\Downloads\esp-spi-flasher (1)\esp-spi-flasher\pc_side\spi_flasher.py", line 260, in handle_serial_message
    raise Exception(f'Unknown message type "{message_type_char}" with data "{message_data}"')
Exception: Unknown message type "I" with data "f this does not help resolve/clarify this issue, please raise an issue at http://www.github.com/Marzogh/SPIMemory/issues with the details of what your were doing when this error occurred"

```

**Comment by rosbeef** [comment]
@samipfjo i would to thank you for your job, sadly as [esp32-bus-pirate ](https://github.com/geo-tp/ESP32-Bus-Pirate) born on fifth july 2025 i does not need any more your project. 

You give me so much energy to understand how work that piece of hardware and spi protocol.
I give you back words to give you energy in your live .

**Comment by samipfjo** [comment]
woah! this is a CRAZY tool! thank you so much for linking it!!

Sep 5, 2025 5:12:55 PM rosbeef andino ***@***.***>:
